### ISSUE TITLE
mistake on keymaster soong namespace

### ISSUE THREAD

**Issue by frostg-012** [ThankYouMario/proprietary_vendor_qcom_common#34]
https://github.com/ThankYouMario/proprietary_vendor_qcom_common/blob/282ff5d0e5428b8bd215f43cf3a8ef63acae5898/vendor/keymaster/keymaster-vendor.mk#L6

it's should be `vendor/qcom/common/vendor/keymaster` right?

**Comment by gotenksIN** [comment]
good catch, we dont have anything in blueprint there so probably went unnoticed because of that
